working_directory: /home/acidburnburn/
live_config_reload: true
window_opacity: 1

env:
  TERM: xterm-256color
window:
  dimensions:
    columns: 80
    lines: 37
  padding:
    x: 20
    y: 15
  dynamic_padding: true
  decorations: none
  dynamic_title: true

scrolling:
  history: 20000
  multiplier: 3

font:
  size: 12.0
  normal:
    family: Anonymous Pro
    style: Regular
  bold:
    family: Anonymous Pro
    style: Bold
  italic:
    family: Anonymous Pro
    style: Italic
  bold_italic:
    family: Anonymous Pro
    style: Bold Italic

colors:
  primary:
    background: "#384242"
    foreground: "#d2d2c2"
  cursor:
    cursor: "#86766e"
  normal:
    black:   '#4d4d4d'
    red:     '#ff4040'
    green:   '#60b48a'
    yellow:  '#efdfaf'
    blue:    '#4ca1be'
    magenta: '#dd8cc3'
    cyan:    '#8cd0d3'
    white:   '#d1d1c2'
  bright:
    black:   '#709080'
    red:     '#dca3a3'
    green:   '#c3bf9f'
    yellow:  '#dfcfa0'
    blue:    '#94bff3'
    magenta: '#ec93d3'
    cyan:    '#93e0e3'
    white:   '#fdfdfd'

  search:
    matches:
      foreground: '#000000'
      background: '#f4f186'
    focused_match:
      foreground: CellBackground
      background: CellForeground

key_bindings:
  - { key: V,          mods: Super,               action: Paste              }
  - { key: C,          mods: Super,               action: Copy               }
  - { key: Escape,     mods: Super,   mode: Vi,   action: ScrollToBottom     }
  - { key: Escape,     mods: Super,               action: ToggleViMode       }
  - { key: Up,         mods: Shift,   mode: ~Alt, action: ScrollHalfPageUp   }
  - { key: Down,       mods: Shift,   mode: ~Alt, action: ScrollHalfPageDown }
  - { key: Slash,      mods: Super,               action: SearchBackward     }

  - { key: Key1, mods: Control, chars: "\x1b[1;6P" }
  - { key: Key2, mods: Control, chars: "\x1b[1;6Q" }
  - { key: Key3, mods: Control, chars: "\x1b[1;6R" }
  - { key: Key4, mods: Control, chars: "\x1b[1;6S" }
  - { key: Key5, mods: Control, chars: "\x1b[15;6~" }
  - { key: Key6, mods: Control, chars: "\x1b[17;6~" }
  - { key: Key7, mods: Control, chars: "\x1b[18;6~" }
  - { key: Key8, mods: Control, chars: "\x1b[19;6~" }
  - { key: Key9, mods: Control, chars: "\x1b[20;6~" }
  - { key: Key0, mods: Control, chars: "\x1b[21;6~" }

debug:
  render_timer: false
