#!/bin/sh

# kill all the tools
pgrep -x sxhkd > /dev/null
pgrep -x tint2 > /dev/null
pgrep -x conky > /dev/null
killall tint2

# run all the tools
feh --bg-fill $HOME/.config/wallpaper.jpg
sxhkd &
tint2 &
conky

# nice cursor
xsetroot -cursor_name left_ptr &

# bspwm
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc monitor -d mai chika misato saki ryuko

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox state=floating desktop='^2'
bspc rule -a physlock manage=off
